export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ASYNC_INCREMET = 'ASYNC_INCREMET'
export const CHANGE_THEME = 'CHANGE_THEME'
export const ENABLE_BTN = 'ENABLE_BTN'
export const DISABLE_BTN = 'DISABLE_BTN'
